#!/usr/bin/env python3
# -*- coding: utf-8 -*-

SCREEN_SIZE = (384, 512)
SCREEN_WIDTH, SCREEN_HEIGHT = SCREEN_SIZE

ENTITY_SIZE = (SCREEN_WIDTH // 12, SCREEN_HEIGHT // 16)
ENTITY_WIDTH, ENTITY_HEIGHT = ENTITY_SIZE